# Generated by Django 2.2.8 on 2020-01-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueId', models.IntegerField(auto_created=True, unique=True)),
                ('issueName', models.CharField(max_length=100)),
                ('issueCreator', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=500)),
                ('contactEmail', models.EmailField(max_length=100)),
                ('Created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
