# Generated by Django 2.2.8 on 2020-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
