# Generated by Django 3.0.5 on 2020-08-06 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0002_auto_20200104_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='email',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='message',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='name',
        ),
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='New issue', max_length=100),
        ),
    ]
