# Generated by Django 3.0.5 on 2020-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0005_auto_20200805_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
